//! Lowering (PORT.md T1.3): post-allocation MIR → a concrete frontend-level
//! [`Cfg`] (temp places rewritten to block 10000 + offset), ready for the T1.2
//! emitter (`emit::cfg_to_engine_nodes`).
//!
//! # Statement regeneration
//!
//! Statements are regenerated as expression trees, the exact inverse of the
//! builder's flattening: each scheduled instruction builds one node whose
//! operand subtrees are spliced in from a per-block *pending* map. A scheduled
//! value used exactly once is consumed into its user's tree; a value never used
//! becomes a standalone statement (bare expression statements are legal in the
//! frontend IR and the emitter evaluates them); `Store`s always become `IRSet`
//! statements. `ShortCircuit` lazy trees are regenerated by an iterative walk
//! of their (single-owner) unscheduled instructions.
//!
//! Because the minimal pipeline does no optimization, this reproduces the same
//! statement and expression shapes the legacy minimal pipeline feeds the
//! emitter (binarized variadic ops are the one shape difference, and all real
//! frontend variadic ops are already binary — see `mir.rs`).
//!
//! # Lowering contract (enforced where cheap, documented otherwise)
//!
//! - No phis ([`LowerError::PhisPresent`]) — out-of-SSA must run first.
//! - Every scheduled non-const value is used at most once, by a later
//!   instruction of the same block or the block's terminator test
//!   ([`LowerError::MultiUse`], [`LowerError::CrossBlockUse`]). Splicing moves
//!   the evaluation point from the schedule slot to the use position, so the
//!   schedule must equal evaluation order — true by construction for
//!   `build_mir` and `ssa::destruct_ssa` output (loads are inserted directly
//!   before their user).
//! - Lazy trees only reference constants and unscheduled instructions of the
//!   same tree ([`LowerError::LazyScheduledRef`], [`LowerError::MultiUse`]).
//! - A dynamic place component (`BlockRef::Value`/`IndexRef::Value`) must be
//!   produced by a `Load` — the encoding-level place grammar only nests places
//!   ([`LowerError::DynamicPlaceNotLoad`]).
//! - Every referenced temp must have an allocated offset
//!   ([`LowerError::UnallocatedTemp`]).
//!
//! # Block order
//!
//! Output blocks are renumbered in reverse postorder with successors visited
//! in `(cond is None, cond)` order — the same traversal the Python encoder and
//! `flow.py` use — so the emitted `JumpLoop` block indexing matches legacy
//! conventions. Branch cases are emitted as sorted edges (ascending cond, then
//! the default), which is what `emit::split_edges` validates.

use std::collections::HashMap;
use std::fmt;

use crate::alloc::{Allocation, TEMP_RUNTIME_BLOCK};
use crate::cfg::{
    BasicBlock, BlockValue, Cfg, Edge, EdgeCond, IndexValue, Node, Place as CfgPlace,
};
use crate::mir::{BlockId, BlockRef, IndexRef, Inst, Mir, Place, TempId, Terminator, Value};
use crate::ops::Op;

/// A lowering failure. All variants indicate MIR outside the lowering contract
/// (impossible for minimal-pipeline MIR; reachable from hand-built MIR).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LowerError {
    /// The MIR still contains phis; run out-of-SSA first.
    PhisPresent,
    /// A scheduled value is referenced more than once (or after an already
    /// consumed splice).
    MultiUse(Value),
    /// A scheduled value is referenced from a different block.
    CrossBlockUse(Value),
    /// A lazy tree references a scheduled value.
    LazyScheduledRef(Value),
    /// A `Phi` appeared inside a lazy tree. (`Store`s are legal there: W4
    /// if-conversion wraps arm statements in `Execute` chains.)
    InvalidLazyInst(Value),
    /// A dynamic place component's tree is not a `Get`.
    DynamicPlaceNotLoad(Value),
    /// A temp place references a temp without an allocated offset.
    UnallocatedTemp(TempId),
}

impl fmt::Display for LowerError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::PhisPresent => write!(f, "MIR still contains phis (out-of-SSA must run first)"),
            Self::MultiUse(v) => write!(f, "scheduled value {v} is used more than once"),
            Self::CrossBlockUse(v) => write!(f, "scheduled value {v} is used across blocks"),
            Self::LazyScheduledRef(v) => write!(f, "lazy tree references scheduled value {v}"),
            Self::InvalidLazyInst(v) => write!(f, "invalid instruction {v} inside a lazy tree"),
            Self::DynamicPlaceNotLoad(v) => {
                write!(f, "dynamic place component {v} is not a load")
            }
            Self::UnallocatedTemp(t) => write!(f, "temp {t} has no allocated offset"),
        }
    }
}

impl std::error::Error for LowerError {}

/// Lowers allocated MIR to a concrete CFG. See the module docs.
///
/// # Errors
///
/// [`LowerError`] when the MIR violates the lowering contract.
pub fn lower_mir(mir: &Mir, alloc: &Allocation) -> Result<Cfg, LowerError> {
    for block in &mir.blocks {
        if !block.phis.is_empty() {
            return Err(LowerError::PhisPresent);
        }
    }
    let mut cfg = Cfg {
        version: crate::decode::ENCODING_VERSION,
        op_count: crate::ops::Op::COUNT,
        ..Cfg::default()
    };
    if mir.blocks.is_empty() {
        return Ok(cfg);
    }

    let order = mir.reverse_postorder();
    let mut block_index: Vec<Option<usize>> = vec![None; mir.blocks.len()];
    for (i, &b) in order.iter().enumerate() {
        block_index[b] = Some(i);
    }

    let scheduled = mir.scheduled_mask();
    let use_counts = count_uses(mir, &scheduled);

    let mut lazy_claimed = vec![false; mir.insts.len()];
    let mut lowerer = Lowerer {
        mir,
        alloc,
        cfg: &mut cfg,
        scheduled: &scheduled,
        lazy_claimed: &mut lazy_claimed,
    };

    let mut out_blocks: Vec<BasicBlock> = Vec::with_capacity(order.len());
    for &b in &order {
        let mut pending: HashMap<Value, usize> = HashMap::new();
        let mut statements: Vec<usize> = Vec::new();
        for &v in &mir.blocks[b].insts {
            let node = lowerer.lower_inst(v, &mut pending)?;
            if use_counts[v as usize] == 0 {
                // No user: a Store statement or a bare expression statement.
                statements.push(node);
            } else {
                pending.insert(v, node);
            }
        }
        let (test, outgoing) =
            lowerer.lower_terminator(&mir.blocks[b].terminator, &block_index, &mut pending)?;
        if let Some(&v) = pending.keys().min() {
            // A pending value was never consumed in its own block: its user
            // (counted by `count_uses`) must live in another block.
            return Err(LowerError::CrossBlockUse(v));
        }
        out_blocks.push(BasicBlock {
            statements,
            test,
            outgoing,
        });
    }
    cfg.blocks = out_blocks;
    Ok(cfg)
}

/// Global use counts over reachable references: immediate operands of
/// scheduled instructions, terminator tests, and operands inside lazy trees.
fn count_uses(mir: &Mir, scheduled: &[bool]) -> Vec<u32> {
    let mut counts = vec![0u32; mir.insts.len()];
    let mut lazy_stack: Vec<Value> = Vec::new();
    for block in &mir.blocks {
        for &v in &block.insts {
            let inst = mir.inst(v);
            Mir::for_each_operand(inst, |o| counts[o as usize] += 1);
            // Count references inside the owned lazy tree(s) as well.
            Mir::for_each_lazy_root(inst, |root| lazy_stack.push(root));
            while let Some(lv) = lazy_stack.pop() {
                if scheduled[lv as usize] || mir.is_const(lv) {
                    continue;
                }
                Mir::for_each_operand(mir.inst(lv), |o| {
                    counts[o as usize] += 1;
                    lazy_stack.push(o);
                });
            }
        }
        if let Terminator::Branch { test, .. } = &block.terminator {
            counts[*test as usize] += 1;
        }
    }
    counts
}

struct Lowerer<'a> {
    mir: &'a Mir,
    alloc: &'a Allocation,
    cfg: &'a mut Cfg,
    scheduled: &'a [bool],
    lazy_claimed: &'a mut [bool],
}

impl Lowerer<'_> {
    fn push_node(&mut self, node: Node) -> usize {
        self.cfg.nodes.push(node);
        self.cfg.nodes.len() - 1
    }

    fn push_place(&mut self, place: CfgPlace) -> usize {
        self.cfg.places.push(place);
        self.cfg.places.len() - 1
    }

    fn const_node(&mut self, v: Value) -> usize {
        match *self.mir.inst(v) {
            Inst::ConstInt(c) => self.push_node(Node::ConstInt(c)),
            Inst::ConstFloat(c) => self.push_node(Node::ConstFloat(c)),
            _ => unreachable!("const_node called on a non-const"),
        }
    }

    /// Resolves an eager operand to its node tree: constants materialize,
    /// scheduled values are consumed from `pending`.
    fn operand(
        &mut self,
        v: Value,
        pending: &mut HashMap<Value, usize>,
    ) -> Result<usize, LowerError> {
        if self.mir.is_const(v) {
            return Ok(self.const_node(v));
        }
        if self.scheduled[v as usize] {
            return pending.remove(&v).ok_or(LowerError::MultiUse(v));
        }
        // An unscheduled non-const in eager position: not part of the contract.
        Err(LowerError::LazyScheduledRef(v))
    }

    /// Rewrites a MIR place to a concrete CFG place, given operand node trees
    /// for any dynamic components.
    fn lower_place(
        &mut self,
        place: &Place,
        block_tree: Option<usize>,
        index_tree: Option<usize>,
    ) -> Result<usize, LowerError> {
        let mut offset = place.offset;
        let block = match place.block {
            BlockRef::Concrete(id) => BlockValue::Int(id),
            BlockRef::Temp(t) => {
                let base = self.alloc.offsets[t].ok_or(LowerError::UnallocatedTemp(t))?;
                offset += i64::from(base);
                BlockValue::Int(TEMP_RUNTIME_BLOCK)
            }
            BlockRef::Value(v) => BlockValue::Place(self.unwrap_get(
                block_tree.expect("block tree was resolved for a dynamic block"),
                v,
            )?),
        };
        let index = match place.index {
            IndexRef::Const(i) => IndexValue::Int(i),
            IndexRef::Value(v) => IndexValue::Place(self.unwrap_get(
                index_tree.expect("index tree was resolved for a dynamic index"),
                v,
            )?),
        };
        Ok(self.push_place(CfgPlace {
            block,
            index,
            offset,
        }))
    }

    /// A dynamic place component must lower to a `Get` (nested place).
    fn unwrap_get(&self, tree: usize, value: Value) -> Result<usize, LowerError> {
        match self.cfg.nodes[tree] {
            Node::Get(place) => Ok(place),
            _ => Err(LowerError::DynamicPlaceNotLoad(value)),
        }
    }

    /// Lowers one scheduled instruction to a node tree.
    fn lower_inst(
        &mut self,
        v: Value,
        pending: &mut HashMap<Value, usize>,
    ) -> Result<usize, LowerError> {
        match self.mir.inst(v).clone() {
            Inst::ConstInt(_) | Inst::ConstFloat(_) => Ok(self.const_node(v)),
            Inst::Op {
                op,
                pure_node,
                args,
            } => {
                let mut arg_trees = Vec::with_capacity(args.len());
                for a in args {
                    arg_trees.push(self.operand(a, pending)?);
                }
                Ok(self.push_node(make_instr(op, pure_node, arg_trees)))
            }
            Inst::ShortCircuit {
                op,
                pure_node,
                lhs,
                rhs,
            } => {
                let lhs_tree = self.operand(lhs, pending)?;
                let rhs_tree = self.lower_lazy_tree(rhs)?;
                Ok(self.push_node(make_instr(op, pure_node, vec![lhs_tree, rhs_tree])))
            }
            Inst::Select {
                test,
                then_root,
                else_root,
            } => {
                // The runtime `If` op as a value node: the interpreter
                // evaluates the test, then only the taken arm (the same node
                // shape the emitter's two-way dispatchers use).
                let test_tree = self.operand(test, pending)?;
                let then_tree = self.lower_lazy_tree(then_root)?;
                let else_tree = self.lower_lazy_tree(else_root)?;
                Ok(self.push_node(make_instr(
                    Op::If,
                    false,
                    vec![test_tree, then_tree, else_tree],
                )))
            }
            Inst::Load { place } => {
                let (block_tree, index_tree) = self.place_components(&place, pending)?;
                let p = self.lower_place(&place, block_tree, index_tree)?;
                Ok(self.push_node(Node::Get(p)))
            }
            Inst::Store { place, value } => {
                let (block_tree, index_tree) = self.place_components(&place, pending)?;
                let value_tree = self.operand(value, pending)?;
                let p = self.lower_place(&place, block_tree, index_tree)?;
                Ok(self.push_node(Node::Set {
                    place: p,
                    value: value_tree,
                }))
            }
            Inst::Phi { .. } => Err(LowerError::PhisPresent),
        }
    }

    /// Resolves the dynamic components of a place (block first, then index —
    /// though both come from `pending`, so order is immaterial here).
    fn place_components(
        &mut self,
        place: &Place,
        pending: &mut HashMap<Value, usize>,
    ) -> Result<(Option<usize>, Option<usize>), LowerError> {
        let block_tree = match place.block {
            BlockRef::Value(v) => Some(self.operand(v, pending)?),
            _ => None,
        };
        let index_tree = match place.index {
            IndexRef::Value(v) => Some(self.operand(v, pending)?),
            IndexRef::Const(_) => None,
        };
        Ok((block_tree, index_tree))
    }

    /// Regenerates a lazy expression tree (`ShortCircuit` rhs, `Select`
    /// arm), iteratively.
    #[allow(clippy::too_many_lines)] // one work-stack state machine
    fn lower_lazy_tree(&mut self, root: Value) -> Result<usize, LowerError> {
        enum Work {
            Visit(Value),
            Finish(Value),
        }
        let mut work = vec![Work::Visit(root)];
        let mut results: Vec<usize> = Vec::new();
        while let Some(item) = work.pop() {
            match item {
                Work::Visit(v) => {
                    if self.mir.is_const(v) {
                        let node = self.const_node(v);
                        results.push(node);
                        continue;
                    }
                    if self.scheduled[v as usize] {
                        return Err(LowerError::LazyScheduledRef(v));
                    }
                    if self.lazy_claimed[v as usize] {
                        return Err(LowerError::MultiUse(v));
                    }
                    self.lazy_claimed[v as usize] = true;
                    work.push(Work::Finish(v));
                    // Children push in reverse so they pop in operand order.
                    match self.mir.inst(v) {
                        Inst::Op { args, .. } => {
                            for &a in args.iter().rev() {
                                work.push(Work::Visit(a));
                            }
                        }
                        Inst::ShortCircuit { lhs, rhs, .. } => {
                            work.push(Work::Visit(*rhs));
                            work.push(Work::Visit(*lhs));
                        }
                        Inst::Select {
                            test,
                            then_root,
                            else_root,
                        } => {
                            work.push(Work::Visit(*else_root));
                            work.push(Work::Visit(*then_root));
                            work.push(Work::Visit(*test));
                        }
                        Inst::Load { place } => {
                            // Index then block (LIFO -> block evaluates first).
                            if let IndexRef::Value(iv) = place.index {
                                work.push(Work::Visit(iv));
                            }
                            if let BlockRef::Value(bv) = place.block {
                                work.push(Work::Visit(bv));
                            }
                        }
                        Inst::Store { place, value } => {
                            // Stores are legal inside W4 if-conversion arm
                            // trees (Execute-wrapped statements evaluated iff
                            // the arm is taken). Legacy Set evaluation order:
                            // block, index, value (LIFO push reverse).
                            work.push(Work::Visit(*value));
                            if let IndexRef::Value(iv) = place.index {
                                work.push(Work::Visit(iv));
                            }
                            if let BlockRef::Value(bv) = place.block {
                                work.push(Work::Visit(bv));
                            }
                        }
                        Inst::Phi { .. } => {
                            return Err(LowerError::InvalidLazyInst(v));
                        }
                        Inst::ConstInt(_) | Inst::ConstFloat(_) => unreachable!(),
                    }
                }
                Work::Finish(v) => match self.mir.inst(v).clone() {
                    Inst::Op {
                        op,
                        pure_node,
                        args,
                    } => {
                        let start = results.len() - args.len();
                        let arg_trees = results.split_off(start);
                        let node = self.push_node(make_instr(op, pure_node, arg_trees));
                        results.push(node);
                    }
                    Inst::ShortCircuit { op, pure_node, .. } => {
                        let rhs_tree = results.pop().expect("rhs tree");
                        let lhs_tree = results.pop().expect("lhs tree");
                        let node =
                            self.push_node(make_instr(op, pure_node, vec![lhs_tree, rhs_tree]));
                        results.push(node);
                    }
                    Inst::Select { .. } => {
                        let else_tree = results.pop().expect("else tree");
                        let then_tree = results.pop().expect("then tree");
                        let test_tree = results.pop().expect("test tree");
                        let node = self.push_node(make_instr(
                            Op::If,
                            false,
                            vec![test_tree, then_tree, else_tree],
                        ));
                        results.push(node);
                    }
                    Inst::Load { place } => {
                        let index_tree = match place.index {
                            IndexRef::Value(_) => Some(results.pop().expect("index tree")),
                            IndexRef::Const(_) => None,
                        };
                        let block_tree = match place.block {
                            BlockRef::Value(_) => Some(results.pop().expect("block tree")),
                            _ => None,
                        };
                        let p = self.lower_place(&place, block_tree, index_tree)?;
                        let node = self.push_node(Node::Get(p));
                        results.push(node);
                    }
                    Inst::Store { place, .. } => {
                        let value_tree = results.pop().expect("store value tree");
                        let index_tree = match place.index {
                            IndexRef::Value(_) => Some(results.pop().expect("index tree")),
                            IndexRef::Const(_) => None,
                        };
                        let block_tree = match place.block {
                            BlockRef::Value(_) => Some(results.pop().expect("block tree")),
                            _ => None,
                        };
                        let p = self.lower_place(&place, block_tree, index_tree)?;
                        // A `Set` node in expression position: the emitter
                        // and interpreter handle it anywhere in a tree (it
                        // evaluates to 0.0; the wrapping Execute discards it).
                        let node = self.push_node(Node::Set {
                            place: p,
                            value: value_tree,
                        });
                        results.push(node);
                    }
                    _ => unreachable!("only Op/ShortCircuit/Select/Load/Store reach Finish"),
                },
            }
        }
        debug_assert_eq!(results.len(), 1);
        Ok(results.pop().expect("lazy tree yields exactly one node"))
    }

    /// Lowers the terminator: the `(test node, edges)` pair of the block.
    fn lower_terminator(
        &mut self,
        terminator: &Terminator,
        block_index: &[Option<usize>],
        pending: &mut HashMap<Value, usize>,
    ) -> Result<(usize, Vec<Edge>), LowerError> {
        let target = |b: BlockId| block_index[b].expect("terminator target is reachable");
        match terminator {
            Terminator::Exit => Ok((self.push_node(Node::ConstInt(0)), Vec::new())),
            Terminator::Jump(t) => Ok((
                self.push_node(Node::ConstInt(0)),
                vec![Edge {
                    cond: EdgeCond::None,
                    target: target(*t),
                }],
            )),
            Terminator::Branch {
                test,
                cases,
                default,
            } => {
                let test_tree = self.operand(*test, pending)?;
                let mut edges: Vec<Edge> = cases
                    .iter()
                    .map(|&(cond, t)| Edge {
                        cond: cond.to_edge_cond(),
                        target: target(t),
                    })
                    .collect();
                if let Some(d) = default {
                    edges.push(Edge {
                        cond: EdgeCond::None,
                        target: target(*d),
                    });
                }
                Ok((test_tree, edges))
            }
        }
    }
}

fn make_instr(op: Op, pure_node: bool, args: Vec<usize>) -> Node {
    if pure_node {
        Node::PureInstr { op, args }
    } else {
        Node::Instr { op, args }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::alloc::allocate_temps;
    use crate::cfg::cfg_to_text;
    use crate::mir::CaseCond;

    fn temp_place(t: TempId) -> Place {
        Place {
            block: BlockRef::Temp(t),
            index: IndexRef::Const(0),
            offset: 0,
        }
    }

    fn sched(mir: &mut Mir, block: usize, inst: Inst) -> Value {
        let v = mir.push_inst(inst);
        mir.blocks[block].insts.push(v);
        v
    }

    fn lower(mir: &Mir) -> Cfg {
        let alloc = allocate_temps(mir).expect("allocation succeeds");
        lower_mir(mir, &alloc).expect("lowering succeeds")
    }

    #[test]
    fn store_load_roundtrip_rewrites_temps() {
        // x = 7; out[2] = x  with x allocated at offset 0 of block 10000.
        let mut mir = Mir::new();
        let x = mir.push_temp("x", 1);
        let b = mir.push_block();
        let c = mir.push_inst(Inst::ConstInt(7));
        sched(
            &mut mir,
            b,
            Inst::Store {
                place: temp_place(x),
                value: c,
            },
        );
        let lx = sched(
            &mut mir,
            b,
            Inst::Load {
                place: temp_place(x),
            },
        );
        sched(
            &mut mir,
            b,
            Inst::Store {
                place: Place {
                    block: BlockRef::Concrete(20),
                    index: IndexRef::Const(2),
                    offset: 0,
                },
                value: lx,
            },
        );
        let cfg = lower(&mir);
        assert_eq!(
            cfg_to_text(&cfg),
            "0:\n  10000[0] <- 7\n  20[2] <- 10000[0]\n  goto exit\n"
        );
    }

    #[test]
    fn place_offsets_compose_with_allocation() {
        // arr (size 4) at base 0; read arr[index dynamic] with offset 2.
        let mut mir = Mir::new();
        let arr = mir.push_temp("arr", 4);
        let idx = mir.push_temp("idx", 1);
        let b = mir.push_block();
        let c = mir.push_inst(Inst::ConstInt(9));
        sched(
            &mut mir,
            b,
            Inst::Store {
                place: temp_place(arr),
                value: c,
            },
        );
        let li = sched(
            &mut mir,
            b,
            Inst::Load {
                place: temp_place(idx),
            },
        );
        let la = sched(
            &mut mir,
            b,
            Inst::Load {
                place: Place {
                    block: BlockRef::Temp(arr),
                    index: IndexRef::Value(li),
                    offset: 2,
                },
            },
        );
        sched(
            &mut mir,
            b,
            Inst::Store {
                place: Place {
                    block: BlockRef::Concrete(20),
                    index: IndexRef::Const(0),
                    offset: 0,
                },
                value: la,
            },
        );
        let cfg = lower(&mir);
        // arr at 0 (size 4), idx at 4. The dynamic-index place keeps its
        // structure: 10000[10000[4] + 2].
        assert_eq!(
            cfg_to_text(&cfg),
            "0:\n  10000[0] <- 9\n  20[0] <- 10000[10000[4] + 2]\n  goto exit\n"
        );
    }

    #[test]
    fn single_use_values_inline_into_their_user() {
        // out = Add(Load(x), 1) regenerates as one nested statement.
        let mut mir = Mir::new();
        let x = mir.push_temp("x", 1);
        let b = mir.push_block();
        let c0 = mir.push_inst(Inst::ConstInt(5));
        sched(
            &mut mir,
            b,
            Inst::Store {
                place: temp_place(x),
                value: c0,
            },
        );
        let lx = sched(
            &mut mir,
            b,
            Inst::Load {
                place: temp_place(x),
            },
        );
        let one = mir.push_inst(Inst::ConstInt(1));
        let add = sched(
            &mut mir,
            b,
            Inst::Op {
                op: Op::Add,
                pure_node: true,
                args: vec![lx, one],
            },
        );
        sched(
            &mut mir,
            b,
            Inst::Store {
                place: Place {
                    block: BlockRef::Concrete(20),
                    index: IndexRef::Const(0),
                    offset: 0,
                },
                value: add,
            },
        );
        let cfg = lower(&mir);
        assert_eq!(cfg.blocks[0].statements.len(), 2);
        assert_eq!(
            cfg_to_text(&cfg),
            "0:\n  10000[0] <- 5\n  20[0] <- Add(10000[0], 1)\n  goto exit\n"
        );
    }

    #[test]
    fn short_circuit_lazy_trees_regenerate_nested() {
        // sc = And(Load(a), And(Load(b), Load(c))) — inner And + b/c loads lazy.
        let mut mir = Mir::new();
        let (a, b_t, c_t) = (
            mir.push_temp("a", 1),
            mir.push_temp("b", 1),
            mir.push_temp("c", 1),
        );
        let blk = mir.push_block();
        for t in [a, b_t, c_t] {
            let c = mir.push_inst(Inst::ConstInt(1));
            sched(
                &mut mir,
                blk,
                Inst::Store {
                    place: temp_place(t),
                    value: c,
                },
            );
        }
        let la = sched(
            &mut mir,
            blk,
            Inst::Load {
                place: temp_place(a),
            },
        );
        let lb = mir.push_inst(Inst::Load {
            place: temp_place(b_t),
        });
        let lc = mir.push_inst(Inst::Load {
            place: temp_place(c_t),
        });
        let inner = mir.push_inst(Inst::ShortCircuit {
            op: Op::And,
            pure_node: true,
            lhs: lb,
            rhs: lc,
        });
        let outer = sched(
            &mut mir,
            blk,
            Inst::ShortCircuit {
                op: Op::And,
                pure_node: true,
                lhs: la,
                rhs: inner,
            },
        );
        sched(
            &mut mir,
            blk,
            Inst::Store {
                place: Place {
                    block: BlockRef::Concrete(20),
                    index: IndexRef::Const(0),
                    offset: 0,
                },
                value: outer,
            },
        );
        let cfg = lower(&mir);
        let text = cfg_to_text(&cfg);
        assert!(
            text.contains("And(10000[0], And(10000[1], 10000[2]))"),
            "nested And must regenerate: {text}"
        );
    }

    #[test]
    fn branch_terminators_emit_sorted_edges_and_test() {
        let mut mir = Mir::new();
        let x = mir.push_temp("x", 1);
        let b0 = mir.push_block();
        let b1 = mir.push_block();
        let b2 = mir.push_block();
        let c = mir.push_inst(Inst::ConstInt(1));
        sched(
            &mut mir,
            b0,
            Inst::Store {
                place: temp_place(x),
                value: c,
            },
        );
        let test = sched(
            &mut mir,
            b0,
            Inst::Load {
                place: temp_place(x),
            },
        );
        mir.blocks[b0].terminator = Terminator::Branch {
            test,
            cases: vec![(CaseCond::Int(0), b2)],
            default: Some(b1),
        };
        mir.blocks[b1].terminator = Terminator::Jump(b2);
        mir.blocks[b2].terminator = Terminator::Exit;
        let cfg = lower(&mir);
        assert_eq!(
            cfg_to_text(&cfg),
            "0:\n  10000[0] <- 1\n  goto 1 if 10000[0] else 2\n1:\n  goto 2\n2:\n  goto exit\n"
        );
    }

    #[test]
    fn rpo_renumbers_blocks_like_the_encoder() {
        // Diamond: 0 -> {1 (cond 0), 2 (default)}; both -> 3. DFS visits the
        // cond-0 successor first (edge sort), so postorder is [3, 1, 2, 0] and
        // the RPO numbering is 0->0, 2->1, 1->2, 3->3 (the first-explored
        // child finishes first and lands *later* in reverse postorder) —
        // matching flow.py/encode.py.
        let mut mir = Mir::new();
        let x = mir.push_temp("x", 1);
        let b0 = mir.push_block();
        let b1 = mir.push_block();
        let b2 = mir.push_block();
        let b3 = mir.push_block();
        let c = mir.push_inst(Inst::ConstInt(1));
        sched(
            &mut mir,
            b0,
            Inst::Store {
                place: temp_place(x),
                value: c,
            },
        );
        let test = sched(
            &mut mir,
            b0,
            Inst::Load {
                place: temp_place(x),
            },
        );
        mir.blocks[b0].terminator = Terminator::Branch {
            test,
            cases: vec![(CaseCond::Int(0), b1)],
            default: Some(b2),
        };
        mir.blocks[b1].terminator = Terminator::Jump(b3);
        mir.blocks[b2].terminator = Terminator::Jump(b3);
        mir.blocks[b3].terminator = Terminator::Exit;
        let cfg = lower(&mir);
        // The default successor is numbered before the cond-0 successor.
        assert_eq!(
            cfg_to_text(&cfg),
            "0:\n  10000[0] <- 1\n  goto 1 if 10000[0] else 2\n1:\n  goto 3\n2:\n  goto 3\n3:\n  goto exit\n"
        );
    }

    #[test]
    fn unreachable_blocks_are_not_emitted() {
        let mut mir = Mir::new();
        let b0 = mir.push_block();
        let _orphan = mir.push_block();
        mir.blocks[b0].terminator = Terminator::Exit;
        let alloc = allocate_temps(&mir).unwrap();
        let cfg = lower_mir(&mir, &alloc).unwrap();
        assert_eq!(cfg.blocks.len(), 1);
    }

    #[test]
    fn phis_are_rejected() {
        let mut mir = Mir::new();
        let b = mir.push_block();
        let phi = mir.push_inst(Inst::Phi { args: vec![] });
        mir.blocks[b].phis.push(phi);
        let alloc = allocate_temps(&mir).unwrap();
        assert_eq!(lower_mir(&mir, &alloc), Err(LowerError::PhisPresent));
    }

    #[test]
    fn multi_use_and_cross_block_uses_are_rejected() {
        // Multi-use: one load consumed by two stores.
        let mut mir = Mir::new();
        let x = mir.push_temp("x", 1);
        let b = mir.push_block();
        let c = mir.push_inst(Inst::ConstInt(1));
        sched(
            &mut mir,
            b,
            Inst::Store {
                place: temp_place(x),
                value: c,
            },
        );
        let lx = sched(
            &mut mir,
            b,
            Inst::Load {
                place: temp_place(x),
            },
        );
        for i in 0..2 {
            sched(
                &mut mir,
                b,
                Inst::Store {
                    place: Place {
                        block: BlockRef::Concrete(20),
                        index: IndexRef::Const(i),
                        offset: 0,
                    },
                    value: lx,
                },
            );
        }
        let alloc = allocate_temps(&mir).unwrap();
        assert_eq!(lower_mir(&mir, &alloc), Err(LowerError::MultiUse(lx)));

        // Cross-block: defined in block 0, consumed in block 1.
        let mut mir = Mir::new();
        let x = mir.push_temp("x", 1);
        let b0 = mir.push_block();
        let b1 = mir.push_block();
        let c = mir.push_inst(Inst::ConstInt(1));
        sched(
            &mut mir,
            b0,
            Inst::Store {
                place: temp_place(x),
                value: c,
            },
        );
        let lx = sched(
            &mut mir,
            b0,
            Inst::Load {
                place: temp_place(x),
            },
        );
        mir.blocks[b0].terminator = Terminator::Jump(b1);
        sched(
            &mut mir,
            b1,
            Inst::Store {
                place: Place {
                    block: BlockRef::Concrete(20),
                    index: IndexRef::Const(0),
                    offset: 0,
                },
                value: lx,
            },
        );
        let alloc = allocate_temps(&mir).unwrap();
        assert_eq!(lower_mir(&mir, &alloc), Err(LowerError::CrossBlockUse(lx)));
    }

    #[test]
    fn deep_schedule_lowers_iteratively() {
        // 150k chained Negates: lowering builds one node per instruction with
        // splicing — no recursion, no quadratic behavior.
        let mut mir = Mir::new();
        let x = mir.push_temp("x", 1);
        let b = mir.push_block();
        let mut v = sched(
            &mut mir,
            b,
            Inst::Load {
                place: temp_place(x),
            },
        );
        for _ in 0..150_000 {
            v = sched(
                &mut mir,
                b,
                Inst::Op {
                    op: Op::Negate,
                    pure_node: true,
                    args: vec![v],
                },
            );
        }
        sched(
            &mut mir,
            b,
            Inst::Store {
                place: Place {
                    block: BlockRef::Concrete(20),
                    index: IndexRef::Const(0),
                    offset: 0,
                },
                value: v,
            },
        );
        let cfg = lower(&mir);
        assert_eq!(cfg.blocks[0].statements.len(), 1);
    }
}
