"""Generate the static op-metadata table for the Cython optimizer core.

Reads ``sonolus/backend/ops.py`` (the ``Op`` ``StrEnum``) and emits two
checked-in, generated files consumed by ``sonolus/backend/_opt/ir.pyx``:

* ``sonolus/backend/_opt/_ops_gen.pxd`` -- a Cython ``cdef`` interface: a C
  ``enum`` giving every op a stable integer id (runtime ops in ``ops.py``
  declaration order, then the synthetic mid-end opcodes ``PHI``/``CONST``/
  ``GET``/``SET``/``UNDEF``), plus ``extern`` declarations of the metadata
  arrays.
* ``sonolus/backend/_opt/_ops_gen.h`` -- the actual ``static const`` C arrays
  (pure/side-effect/control-flow flags + names). These are GIL-free to read
  from ``nogil`` pass code and live entirely in read-only static storage.

A ``.pxd`` cannot hold array *definitions* (only declarations), so the data
lives in the companion header and the ``.pxd`` declares it via
``cdef extern from "_ops_gen.h"``. Both files are regenerated together and a
unit test (``tests/backend/test_ops_sync.py``) asserts the checked-in copies
match ``ops.py`` (run ``python tools/gen_ops.py`` to regenerate).

See OPTIMIZER_REWRITE.md section 6.1.
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from sonolus.backend.ops import Op

# Synthetic mid-end opcodes occupying an extended opcode space above the runtime
# ops. Order is stable; ids are assigned right after the runtime ops.
SYNTHETIC_OPS = ("PHI", "CONST", "GET", "SET", "UNDEF")

_OPT_DIR = _REPO_ROOT / "sonolus" / "backend" / "_opt"
PXD_PATH = _OPT_DIR / "_ops_gen.pxd"
HEADER_PATH = _OPT_DIR / "_ops_gen.h"

_AUTOGEN_NOTE = "Auto-generated by tools/gen_ops.py from sonolus/backend/ops.py. Do not edit by hand."


def _runtime_ops() -> list[Op]:
    return list(Op)


def _enum_ident(name: str) -> str:
    return f"OP_{name}"


def generate_pxd() -> str:
    ops = _runtime_ops()
    lines: list[str] = []
    lines.append("# cython: language_level=3")
    lines.append(f"# {_AUTOGEN_NOTE}")
    lines.append("")
    lines.append("# Stable integer id for every opcode. Runtime ops come first, in ops.py")
    lines.append("# declaration order (id == enumeration index); the synthetic mid-end opcodes")
    lines.append("# follow. OP_TABLE_SIZE is the total, and the metadata arrays are sized to it.")
    lines.append("cdef enum:")
    for i, op in enumerate(ops):
        lines.append(f"    {_enum_ident(op.value)} = {i}")
    next_id = len(ops)
    for offset, name in enumerate(SYNTHETIC_OPS):
        lines.append(f"    OPX_{name} = {next_id + offset}")
    lines.append(f"    OP_RUNTIME_COUNT = {len(ops)}")
    lines.append(f"    OP_TABLE_SIZE = {len(ops) + len(SYNTHETIC_OPS)}")
    lines.append("")
    lines.append('cdef extern from "_ops_gen.h":')
    lines.append("    const unsigned char SONOLUS_OP_PURE[OP_TABLE_SIZE]")
    lines.append("    const unsigned char SONOLUS_OP_SIDE_EFFECTS[OP_TABLE_SIZE]")
    lines.append("    const unsigned char SONOLUS_OP_CONTROL_FLOW[OP_TABLE_SIZE]")
    lines.append("    const char* SONOLUS_OP_NAMES[OP_TABLE_SIZE]")
    lines.append("")
    return "\n".join(lines)


def _c_bool_array(name: str, values: list[int]) -> str:
    body = ", ".join(str(v) for v in values)
    return f"static const unsigned char {name}[{len(values)}] = {{{body}}};"


def generate_header() -> str:
    ops = _runtime_ops()
    total = len(ops) + len(SYNTHETIC_OPS)

    pure = [1 if op.pure else 0 for op in ops] + [0] * len(SYNTHETIC_OPS)
    side = [1 if op.side_effects else 0 for op in ops] + [0] * len(SYNTHETIC_OPS)
    control = [1 if op.control_flow else 0 for op in ops] + [0] * len(SYNTHETIC_OPS)

    # Synthetic opcode metadata: CONST/GET are pure-ish values, SET is a store,
    # PHI/UNDEF are structural. These flags are placeholders for the mid-end
    # (M2) which classifies them explicitly; the runtime-op flags are what M1
    # relies on. Mark CONST pure so a lone constant is trivially movable.
    synthetic_pure = {"CONST": 1}
    for offset, name in enumerate(SYNTHETIC_OPS):
        pure[len(ops) + offset] = synthetic_pure.get(name, 0)

    names = [op.value for op in ops] + list(SYNTHETIC_OPS)

    lines: list[str] = []
    lines.append(f"/* {_AUTOGEN_NOTE} */")
    lines.append("#ifndef SONOLUS_OPT_OPS_GEN_H")
    lines.append("#define SONOLUS_OPT_OPS_GEN_H")
    lines.append("")
    lines.append(_c_bool_array("SONOLUS_OP_PURE", pure))
    lines.append(_c_bool_array("SONOLUS_OP_SIDE_EFFECTS", side))
    lines.append(_c_bool_array("SONOLUS_OP_CONTROL_FLOW", control))
    lines.append("")
    names_body = ", ".join(f'"{n}"' for n in names)
    lines.append(f"static const char* const SONOLUS_OP_NAMES[{total}] = {{{names_body}}};")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def generate() -> dict[Path, str]:
    """Return the generated file contents keyed by absolute path."""
    return {
        PXD_PATH: generate_pxd(),
        HEADER_PATH: generate_header(),
    }


def main() -> None:
    for path, content in generate().items():
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(_REPO_ROOT)}")


if __name__ == "__main__":
    main()
