"""Generates the Rust `Op` enum from `sonolus/backend/ops.py`.

Run from the repo root:

    uv run python tools/gen_ops.py

writes `rust/sonolus-backend-core/src/ops.rs` (LF line endings, UTF-8). Pass `--check`
to verify the checked-in file is up to date without writing (exit code 1 on mismatch).

The output is a pure function of `sonolus.backend.ops.Op`: ops are emitted in definition
order, and each op's numeric id is its 0-based definition-order index. The CFG binary
encoding (rust/ENCODING.md) serializes ops by these ids, so the assignment must stay
stable; `tests/backend/test_ops_sync.py` fails whenever the checked-in file is stale.

The emitted code is rustfmt-clean as written (one enum variant / match arm per line,
within rustfmt's default 100-column width), so regeneration never needs a `cargo fmt`
pass and `cargo fmt --check` passes on the checked-in file.
"""

import argparse
import re
import sys
from collections.abc import Iterable
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "rust" / "sonolus-backend-core" / "src" / "ops.rs"

RUST_IDENT_RE = re.compile(r"[A-Za-z][A-Za-z0-9]*")

HEADER = """\
//! Sonolus engine node operations, mirroring `sonolus.backend.ops.Op`.
//!
//! GENERATED FILE — DO NOT EDIT.
//! Generated by `tools/gen_ops.py` from `sonolus/backend/ops.py`; regenerate with
//! `uv run python tools/gen_ops.py`. The sync test `tests/backend/test_ops_sync.py`
//! fails when this file is stale.
//!
//! Op ids are stable: each op's id is its 0-based definition-order index in
//! `sonolus/backend/ops.py`. The CFG binary encoding (see `rust/ENCODING.md`) serializes
//! ops by these ids, so reordering or removing entries in `ops.py` changes the encoding
//! and requires an encoding version bump; new ops must only ever be appended.
#![allow(clippy::too_many_lines)]"""


def _rust_bool(value: bool) -> str:
    return "true" if value else "false"


def generate() -> str:
    """Returns the full contents of the generated `ops.rs` file."""
    from sonolus.backend.ops import Op

    ops = list(Op)
    if len(ops) >= 0x10000:
        raise ValueError("op ids no longer fit in u16; the CFG encoding must change")
    for op in ops:
        if op.name != op.value:
            raise ValueError(f"op name/value mismatch: {op.name!r} != {op.value!r}")
        if not RUST_IDENT_RE.fullmatch(op.name):
            raise ValueError(f"op name is not a valid Rust identifier: {op.name!r}")

    lines: list[str] = [HEADER]

    def emit(text: str, body: Iterable[str] = ()) -> None:
        lines.append(text)
        lines.extend(body)

    emit("")
    emit("/// A Sonolus engine node operation.")
    emit("///")
    emit("/// Mirrors `sonolus.backend.ops.Op`; the discriminant of each variant is the op's")
    emit("/// stable numeric id (see the module docs).")
    emit("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]")
    emit("#[repr(u16)]")
    emit("pub enum Op {", (f"    {op.name} = {i}," for i, op in enumerate(ops)))
    emit("}")
    emit("")
    emit("impl Op {")
    emit("    /// The number of ops; valid ids are exactly `0..COUNT`.")
    emit(f"    pub const COUNT: u16 = {len(ops)};")
    emit("")
    emit("    /// The stable numeric id of this op.")
    emit("    pub const fn id(self) -> u16 {")
    emit("        self as u16")
    emit("    }")
    emit("")
    emit("    /// The op name as it appears in engine data and `sonolus.backend.ops.Op`.")
    emit("    pub const fn name(self) -> &'static str {")
    emit("        self.info().0")
    emit("    }")
    emit("")
    emit("    /// Whether this op has side effects (mirrors `Op.side_effects`).")
    emit("    pub const fn side_effects(self) -> bool {")
    emit("        self.info().1")
    emit("    }")
    emit("")
    emit("    /// Whether this op is pure (mirrors `Op.pure`).")
    emit("    pub const fn pure(self) -> bool {")
    emit("        self.info().2")
    emit("    }")
    emit("")
    emit("    /// Whether this op participates in control flow (mirrors `Op.control_flow`).")
    emit("    pub const fn control_flow(self) -> bool {")
    emit("        self.info().3")
    emit("    }")
    emit("")
    emit("    /// All ops in ascending id order.")
    emit("    pub fn all() -> impl Iterator<Item = Self> {")
    emit("        (0..Self::COUNT).filter_map(Self::from_id)")
    emit("    }")
    emit("")
    emit("    /// Looks up an op by its stable numeric id.")
    emit("    pub const fn from_id(id: u16) -> Option<Self> {")
    emit("        match id {", (f"            {i} => Some(Self::{op.name})," for i, op in enumerate(ops)))
    emit("            _ => None,")
    emit("        }")
    emit("    }")
    emit("")
    emit("    /// Looks up an op by name.")
    emit("    pub fn from_name(name: &str) -> Option<Self> {")
    emit("        match name {", (f'            "{op.name}" => Some(Self::{op.name}),' for op in ops))
    emit("            _ => None,")
    emit("        }")
    emit("    }")
    emit("")
    emit("    /// `(name, side_effects, pure, control_flow)` of this op.")
    emit("    const fn info(self) -> (&'static str, bool, bool, bool) {")
    emit(
        "        match self {",
        (
            f'            Self::{op.name} => ("{op.name}", {_rust_bool(op.side_effects)},'
            f" {_rust_bool(op.pure)}, {_rust_bool(op.control_flow)}),"
            for op in ops
        ),
    )
    emit("        }")
    emit("    }")
    emit("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the checked-in file matches instead of writing it",
    )
    args = parser.parse_args()

    content = generate().encode("utf-8")
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_bytes() != content:
            print(
                f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is out of date; run `uv run python tools/gen_ops.py`",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is up to date")
        return 0
    OUTPUT_PATH.write_bytes(content)
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
