"""Generate the static op-metadata table for the Cython optimizer core.

Reads ``sonolus/backend/ops.py`` (the ``Op`` ``StrEnum``) and emits two
checked-in, generated files consumed by ``sonolus/backend/_opt/ir.pyx``:

* ``sonolus/backend/_opt/_ops_gen.pxd`` -- a Cython ``cdef`` interface: a C
  ``enum`` giving every op a stable integer id (runtime ops in ``ops.py``
  declaration order, then the synthetic mid-end opcodes ``PHI``/``CONST``/
  ``GET``/``SET``/``UNDEF``), plus ``extern`` declarations of the metadata
  arrays.
* ``sonolus/backend/_opt/_ops_gen.h`` -- the actual ``static const`` C arrays
  (pure/side-effect/control-flow flags + names). These are GIL-free to read
  from ``nogil`` pass code and live entirely in read-only static storage.

A ``.pxd`` cannot hold array *definitions* (only declarations), so the data
lives in the companion header and the ``.pxd`` declares it via
``cdef extern from "_ops_gen.h"``. Both files are regenerated together and a
unit test (``tests/backend/test_ops_sync.py``) asserts the checked-in copies
match ``ops.py`` (run ``python tools/gen_ops.py`` to regenerate).
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from sonolus.backend.ops import Op

# Synthetic mid-end opcodes occupying an extended opcode space above the runtime
# ops. Order is stable; ids are assigned right after the runtime ops.
SYNTHETIC_OPS = ("PHI", "CONST", "GET", "SET", "UNDEF")

_OPT_DIR = _REPO_ROOT / "sonolus" / "backend" / "_opt"
PXD_PATH = _OPT_DIR / "_ops_gen.pxd"
HEADER_PATH = _OPT_DIR / "_ops_gen.h"

_AUTOGEN_NOTE = "Auto-generated by tools/gen_ops.py from sonolus/backend/ops.py. Do not edit by hand."

# --------------------------------------------------------------------------
# Foldability table.
#
# A FOLDABLE op is pure AND data-independent: its value is a total function of
# its operand values, so an all-constant-operand instance folds to a constant
# at compile time. This is exactly the set the C fold kernels (kernels.pyx)
# evaluate, and the set SCCP is allowed to constant-fold.
#
# The count is fixed at 84: the 42-op core list below, six additions (Sign,
# Trunc, Unlerp, UnlerpClamped, Judge, JudgeSimple), and the 36 Ease* ops.
#
# NOT foldable, though pure: environment-dependent ops (BeatTo*/TimeTo*, Has*,
# stream reads) whose value depends on runtime state, and the control-flow ops
# (If/Switch*/Execute*/While/DoWhile/JumpLoop/Block/Break), which are not
# value-producing constant folds. NB: And/Or have control_flow=True yet ARE
# foldable (short-circuit *value* ops, part of the SCCP-42) -- foldability is
# an explicit allow-list, not derived from the control_flow flag.
# --------------------------------------------------------------------------

# The 42-op core of the foldable set (kept as an explicit list so drift fails loudly).
_SCCP_SUPPORTED_42 = (
    "Equal", "NotEqual", "Greater", "GreaterOr", "Less", "LessOr", "Not", "And", "Or",
    "Negate", "Add", "Subtract", "Multiply", "Divide", "Power", "Log", "Ceil", "Floor",
    "Round", "Frac", "Mod", "Rem", "Sin", "Cos", "Tan", "Sinh", "Cosh", "Tanh",
    "Arcsin", "Arccos", "Arctan", "Arctan2", "Max", "Min", "Abs", "Clamp", "Degree",
    "Radian", "Lerp", "LerpClamped", "Remap", "RemapClamped",
)  # fmt: skip

# The six ops folded by the rewrite beyond SCCP-42, besides the Ease* family.
_FOLDABLE_ADDITIONS = ("Sign", "Trunc", "Unlerp", "UnlerpClamped", "Judge", "JudgeSimple")

# Pure ops that must NEVER be folded because their value depends on the runtime
# environment (not just their operands).
_ENV_DEPENDENT = frozenset(
    {
        "BeatToBPM", "BeatToStartingBeat", "BeatToStartingTime", "BeatToTime",
        "TimeToScaledTime", "TimeToStartingScaledTime", "TimeToStartingTime", "TimeToTimeScale",
        "HasEffectClip", "HasParticleEffect", "HasSkinSprite",
        "StreamGetNextKey", "StreamGetPreviousKey", "StreamGetValue", "StreamHas",
    }
)  # fmt: skip

# Structural / control-flow ops (never a value fold). Most are control_flow=True;
# Execute/Execute0 are pure sequencing ops (control_flow=False) that still never
# fold. And/Or are excluded from this list deliberately -- they are foldable
# value ops despite control_flow=True.
_STRUCTURAL_NONFOLDABLE = (
    "If", "Switch", "SwitchInteger", "SwitchIntegerWithDefault", "SwitchWithDefault",
    "Execute", "Execute0", "While", "DoWhile", "JumpLoop", "Block", "Break",
)  # fmt: skip

FOLDABLE_COUNT = 84


def foldable_op_names() -> list[str]:
    """Ordered list of foldable op *names* (ops.py declaration order).

    Derived programmatically (SCCP-42 + six additions + every ``Ease*`` op) then
    hard-asserted for exact count, purity, and the exclusions so the generator
    (and, via ``tests/backend/test_ops_sync.py``, CI) fails loudly on drift.
    """
    all_names = [op.value for op in Op]
    by_name = {op.value: op for op in Op}

    ease = [n for n in all_names if n.startswith("Ease")]
    assert len(ease) == 36, f"expected 36 Ease* ops, found {len(ease)}"

    assert len(_SCCP_SUPPORTED_42) == 42
    assert len(set(_SCCP_SUPPORTED_42)) == 42

    foldable = set(_SCCP_SUPPORTED_42) | set(_FOLDABLE_ADDITIONS) | set(ease)
    assert len(foldable) == FOLDABLE_COUNT, f"expected {FOLDABLE_COUNT} foldable ops, found {len(foldable)}"

    # Every foldable op must be a real, pure Op.
    for name in foldable:
        assert name in by_name, f"foldable op {name!r} is not a real Op"
        assert by_name[name].pure, f"foldable op {name!r} must be pure"

    # Environment-dependent pure ops are pure but excluded.
    for name in _ENV_DEPENDENT:
        assert name in by_name, f"{name!r} should be a real Op"
        assert by_name[name].pure, f"{name!r} should be a pure Op"
        assert name not in foldable, f"env-dependent op {name!r} must not be foldable"

    # Structural / control-flow ops are excluded; And/Or are the deliberate exception.
    for name in _STRUCTURAL_NONFOLDABLE:
        assert name in by_name, f"{name!r} should be a real Op"
        assert name not in foldable, f"structural op {name!r} must not be foldable"
    assert "And" in foldable, "And must be foldable"
    assert "Or" in foldable, "Or must be foldable"
    assert by_name["And"].control_flow, "And is control_flow"
    assert by_name["Or"].control_flow, "Or is control_flow"

    return [n for n in all_names if n in foldable]


def _runtime_ops() -> list[Op]:
    return list(Op)


def _enum_ident(name: str) -> str:
    return f"OP_{name}"


def generate_pxd() -> str:
    ops = _runtime_ops()
    lines: list[str] = []
    lines.append("# cython: language_level=3")
    lines.append(f"# {_AUTOGEN_NOTE}")
    lines.append("")
    lines.append("# Stable integer id for every opcode. Runtime ops come first, in ops.py")
    lines.append("# declaration order (id == enumeration index); the synthetic mid-end opcodes")
    lines.append("# follow. OP_TABLE_SIZE is the total, and the metadata arrays are sized to it.")
    lines.append("cdef enum:")
    for i, op in enumerate(ops):
        lines.append(f"    {_enum_ident(op.value)} = {i}")
    next_id = len(ops)
    for offset, name in enumerate(SYNTHETIC_OPS):
        lines.append(f"    OPX_{name} = {next_id + offset}")
    lines.append(f"    OP_RUNTIME_COUNT = {len(ops)}")
    lines.append(f"    OP_TABLE_SIZE = {len(ops) + len(SYNTHETIC_OPS)}")
    lines.append("")
    lines.append('cdef extern from "_ops_gen.h":')
    lines.append("    const unsigned char SONOLUS_OP_PURE[OP_TABLE_SIZE]")
    lines.append("    const unsigned char SONOLUS_OP_SIDE_EFFECTS[OP_TABLE_SIZE]")
    lines.append("    const unsigned char SONOLUS_OP_CONTROL_FLOW[OP_TABLE_SIZE]")
    lines.append("    const unsigned char SONOLUS_OP_FOLDABLE[OP_TABLE_SIZE]")
    lines.append("    const char* SONOLUS_OP_NAMES[OP_TABLE_SIZE]")
    lines.append("")
    return "\n".join(lines)


def _c_bool_array(name: str, values: list[int]) -> str:
    body = ", ".join(str(v) for v in values)
    return f"static const unsigned char {name}[{len(values)}] = {{{body}}};"


def generate_header() -> str:
    ops = _runtime_ops()
    total = len(ops) + len(SYNTHETIC_OPS)

    pure = [1 if op.pure else 0 for op in ops] + [0] * len(SYNTHETIC_OPS)
    side = [1 if op.side_effects else 0 for op in ops] + [0] * len(SYNTHETIC_OPS)
    control = [1 if op.control_flow else 0 for op in ops] + [0] * len(SYNTHETIC_OPS)

    # Data-independent pure ops the C fold kernels evaluate (see foldable_op_names).
    # No synthetic opcode is foldable.
    foldable_names = set(foldable_op_names())
    foldable = [1 if op.value in foldable_names else 0 for op in ops] + [0] * len(SYNTHETIC_OPS)

    # Synthetic opcode metadata: CONST/GET are pure-ish values, SET is a store,
    # PHI/UNDEF are structural. These flags are placeholders -- the mid-end
    # classifies synthetic opcodes explicitly rather than consulting this table.
    # Mark CONST pure so a lone constant is trivially movable.
    synthetic_pure = {"CONST": 1}
    for offset, name in enumerate(SYNTHETIC_OPS):
        pure[len(ops) + offset] = synthetic_pure.get(name, 0)

    names = [op.value for op in ops] + list(SYNTHETIC_OPS)

    lines: list[str] = []
    lines.append(f"/* {_AUTOGEN_NOTE} */")
    lines.append("#ifndef SONOLUS_OPT_OPS_GEN_H")
    lines.append("#define SONOLUS_OPT_OPS_GEN_H")
    lines.append("")
    lines.append(_c_bool_array("SONOLUS_OP_PURE", pure))
    lines.append(_c_bool_array("SONOLUS_OP_SIDE_EFFECTS", side))
    lines.append(_c_bool_array("SONOLUS_OP_CONTROL_FLOW", control))
    lines.append(_c_bool_array("SONOLUS_OP_FOLDABLE", foldable))
    lines.append("")
    names_body = ", ".join(f'"{n}"' for n in names)
    lines.append(f"static const char* const SONOLUS_OP_NAMES[{total}] = {{{names_body}}};")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def generate() -> dict[Path, str]:
    """Return the generated file contents keyed by absolute path."""
    return {
        PXD_PATH: generate_pxd(),
        HEADER_PATH: generate_header(),
    }


def main() -> None:
    for path, content in generate().items():
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(_REPO_ROOT)}")


if __name__ == "__main__":
    main()
